// <auto-generated />
using System;
using MVCDHProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCDHProject.Migrations
{
    [DbContext(typeof(MVCCoreDbContext))]
    [Migration("20221215091224_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MVCDHProject.Models.Customer", b =>
                {
                    b.Property<int>("Custid")
                        .HasColumnType("int");

                    b.Property<decimal?>("Balance")
                        .HasColumnType("Money");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Custid");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Custid = 101,
                            Balance = 50000.00m,
                            City = "Delhi",
                            Name = "Sai",
                            Status = true
                        },
                        new
                        {
                            Custid = 102,
                            Balance = 50000.00m,
                            City = "Mumbai",
                            Name = "Pratik",
                            Status = true
                        },
                        new
                        {
                            Custid = 103,
                            Balance = 50000.00m,
                            City = "Bangalore",
                            Name = "Mohan",
                            Status = true
                        },
                        new
                        {
                            Custid = 104,
                            Balance = 50000.00m,
                            City = "Kolkatta",
                            Name = "Mrunal",
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
